---
title: "analysis_mtcars"
output: pdf_document
---

```{r setup, include=FALSE}
library(coda)
library(quantreg)

rm(list=ls())
data(mtcars)
```

Setup
```{r}
itr_total = 12000
quantiles=c(0.1, 0.5, 0.9)
dist_eps_list=c("stdN","student","heteroN")
d=4
burn_in=2000

simulation1 = data.frame("Distribution_Eps"=character(0), "Method"=character(0),
                         "p"=numeric(), 
                         "beta1_MCSE"=numeric(), "beta1_IF"=numeric(), "beta1_mu"=numeric(), 
                         "beta1_sd"=numeric(), "beta1_last"=numeric(),
                         "beta2_MCSE"=numeric(), "beta2_IF"=numeric(), "beta2_mu"=numeric(),
                         "beta2_sd"=numeric(),
                         "beta2_last"=numeric(), 
                         "beta3_MCSE"=numeric(), "beta3_IF"=numeric(), "beta3_mu"=numeric(),
                         "beta3_sd"=numeric(),
                         "beta3_last"=numeric(),
                         "beta4_MCSE"=numeric(), "beta4_IF"=numeric(), "beta4_mu"=numeric(),
                         "beta4_sd"=numeric(),
                         "beta4_last"=numeric(),stringsAsFactors=F)

```

Append data
```{r}
for (p in quantiles){
    for (dist_eps in dist_eps_list){
        load(paste0("C:\\Users\\juyil\\Documents\\la\\R\\mtcars\\Gibbs with Scale\\","GWS_",p,"_",dist_eps,"_betap.RData"))
        beta_p = list()
        for (i in 1:d){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[(burn_in+1):itr_total]
          # plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "GWS", as.numeric(p), 
                    as.numeric(mcse(beta_p[[1]])$se), as.numeric(length(beta_p[[1]])/effectiveSize(beta_p[[1]])), 
                    as.numeric(mean(beta_p[[1]])), as.numeric(sd(beta_p[[1]])),
                    as.numeric(beta_p[[1]][length(beta_p[[1]])]),
                    as.numeric(mcse(beta_p[[2]])$se), as.numeric(length(beta_p[[2]])/effectiveSize(beta_p[[2]])),
                    as.numeric(mean(beta_p[[2]])), as.numeric(sd(beta_p[[2]])),
                    as.numeric(beta_p[[2]][length(beta_p[[2]])]),
                    as.numeric(mcse(beta_p[[3]])$se), as.numeric(length(beta_p[[3]])/effectiveSize(beta_p[[3]])), 
                    as.numeric(mean(beta_p[[3]])), as.numeric(sd(beta_p[[3]])),
                    as.numeric(beta_p[[3]][length(beta_p[[3]])]),
                    as.numeric(mcse(beta_p[[4]])$se), as.numeric(length(beta_p[[4]])/effectiveSize(beta_p[[4]])), 
                    as.numeric(mean(beta_p[[4]])), as.numeric(sd(beta_p[[4]])),
                    as.numeric(beta_p[[4]][length(beta_p[[4]])]))
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################   
        load(paste0("C:\\Users\\juyil\\Documents\\la\\R\\mtcars\\Gibbs without Scale\\","GWOS_",p,"_",dist_eps,"_betap.RData"))
        beta_p = list()
        for (i in 1:d){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[(burn_in+1):itr_total]
          # plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "GWOS", as.numeric(p), 
                    as.numeric(mcse(beta_p[[1]])$se), as.numeric(length(beta_p[[1]])/effectiveSize(beta_p[[1]])), 
                    as.numeric(mean(beta_p[[1]])), as.numeric(sd(beta_p[[1]])),
                    as.numeric(beta_p[[1]][length(beta_p[[1]])]),
                    as.numeric(mcse(beta_p[[2]])$se), as.numeric(length(beta_p[[2]])/effectiveSize(beta_p[[2]])),
                    as.numeric(mean(beta_p[[2]])), as.numeric(sd(beta_p[[2]])),
                    as.numeric(beta_p[[2]][length(beta_p[[2]])]),
                    as.numeric(mcse(beta_p[[3]])$se), as.numeric(length(beta_p[[3]])/effectiveSize(beta_p[[3]])), 
                    as.numeric(mean(beta_p[[3]])), as.numeric(sd(beta_p[[3]])),
                    as.numeric(beta_p[[3]][length(beta_p[[3]])]),
                    as.numeric(mcse(beta_p[[4]])$se), as.numeric(length(beta_p[[4]])/effectiveSize(beta_p[[4]])), 
                    as.numeric(mean(beta_p[[4]])), as.numeric(sd(beta_p[[4]])),
                    as.numeric(beta_p[[4]][length(beta_p[[4]])]))
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################
        load(paste0("C:\\Users\\juyil\\Documents\\la\\R\\mtcars\\Double Exponential Prior\\","DEP_",p,"_",dist_eps,"_betap.RData"))
        beta_p = list()
        for (i in 1:d){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[(burn_in+1):itr_total]
          # plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "DEP", as.numeric(p),
                    as.numeric(mcse(beta_p[[1]])$se), as.numeric(length(beta_p[[1]])/effectiveSize(beta_p[[1]])), 
                    as.numeric(mean(beta_p[[1]])), as.numeric(sd(beta_p[[1]])),
                    as.numeric(beta_p[[1]][length(beta_p[[1]])]),
                    as.numeric(mcse(beta_p[[2]])$se), as.numeric(length(beta_p[[2]])/effectiveSize(beta_p[[2]])),
                    as.numeric(mean(beta_p[[2]])), as.numeric(sd(beta_p[[2]])),
                    as.numeric(beta_p[[2]][length(beta_p[[2]])]),
                    as.numeric(mcse(beta_p[[3]])$se), as.numeric(length(beta_p[[3]])/effectiveSize(beta_p[[3]])), 
                    as.numeric(mean(beta_p[[3]])), as.numeric(sd(beta_p[[3]])),
                    as.numeric(beta_p[[3]][length(beta_p[[3]])]),
                    as.numeric(mcse(beta_p[[4]])$se), as.numeric(length(beta_p[[4]])/effectiveSize(beta_p[[4]])), 
                    as.numeric(mean(beta_p[[4]])), as.numeric(sd(beta_p[[4]])),
                    as.numeric(beta_p[[4]][length(beta_p[[4]])]))
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################
        load(paste0("C:\\Users\\juyil\\Documents\\la\\R\\mtcars\\Tobit with Scale\\","TWS_",p,"_",dist_eps,"_betap.RData"))
        beta_p = list()
        for (i in 1:d){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[(burn_in+1):itr_total]
          # plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "TWS", as.numeric(p), 
                    as.numeric(mcse(beta_p[[1]])$se), as.numeric(length(beta_p[[1]])/effectiveSize(beta_p[[1]])), 
                    as.numeric(mean(beta_p[[1]])), as.numeric(sd(beta_p[[1]])),
                    as.numeric(beta_p[[1]][length(beta_p[[1]])]),
                    as.numeric(mcse(beta_p[[2]])$se), as.numeric(length(beta_p[[2]])/effectiveSize(beta_p[[2]])),
                    as.numeric(mean(beta_p[[2]])), as.numeric(sd(beta_p[[2]])),
                    as.numeric(beta_p[[2]][length(beta_p[[2]])]),
                    as.numeric(mcse(beta_p[[3]])$se), as.numeric(length(beta_p[[3]])/effectiveSize(beta_p[[3]])), 
                    as.numeric(mean(beta_p[[3]])), as.numeric(sd(beta_p[[3]])),
                    as.numeric(beta_p[[3]][length(beta_p[[3]])]),
                    as.numeric(mcse(beta_p[[4]])$se), as.numeric(length(beta_p[[4]])/effectiveSize(beta_p[[4]])), 
                    as.numeric(mean(beta_p[[4]])), as.numeric(sd(beta_p[[4]])),
                    as.numeric(beta_p[[4]][length(beta_p[[4]])]))
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################
        load(paste0("C:\\Users\\juyil\\Documents\\la\\R\\mtcars\\Tobit without Scale\\","TWOS_",p,"_",dist_eps,"_betap.RData"))
        beta_p = list()
        for (i in 1:d){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[(burn_in+1):itr_total]
          # plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "TWOS", as.numeric(p), 
                    as.numeric(mcse(beta_p[[1]])$se), as.numeric(length(beta_p[[1]])/effectiveSize(beta_p[[1]])), 
                    as.numeric(mean(beta_p[[1]])), as.numeric(sd(beta_p[[1]])),
                    as.numeric(beta_p[[1]][length(beta_p[[1]])]),
                    as.numeric(mcse(beta_p[[2]])$se), as.numeric(length(beta_p[[2]])/effectiveSize(beta_p[[2]])),
                    as.numeric(mean(beta_p[[2]])), as.numeric(sd(beta_p[[2]])),
                    as.numeric(beta_p[[2]][length(beta_p[[2]])]),
                    as.numeric(mcse(beta_p[[3]])$se), as.numeric(length(beta_p[[3]])/effectiveSize(beta_p[[3]])), 
                    as.numeric(mean(beta_p[[3]])), as.numeric(sd(beta_p[[3]])),
                    as.numeric(beta_p[[3]][length(beta_p[[3]])]),
                    as.numeric(mcse(beta_p[[4]])$se), as.numeric(length(beta_p[[4]])/effectiveSize(beta_p[[4]])), 
                    as.numeric(mean(beta_p[[4]])), as.numeric(sd(beta_p[[4]])),
                    as.numeric(beta_p[[4]][length(beta_p[[4]])]))
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################
        
    }
}

```

Clean
```{r}
ord = c("stdN","heteroN","student")
simulation1$Distribution_Eps = factor(simulation1$Distribution_Eps,levels=ord)
simulation1 = simulation1[order(simulation1$Distribution_Eps),]
is.num <- sapply(simulation1, is.numeric)
simulation1[is.num] <- lapply(simulation1[is.num], round, 4)
simulation1

```



quantreg
```{r}
rqfit <- rq(mpg ~ cyl+drat+vs, data = mtcars, tau = quantiles)
summary(rqfit)


```