---
title: "analysis"
output: pdf_document
---

```{r setup, include=FALSE}
library(coda)
library(mcmcse)
rm(list=ls())
setwd('C:\\Users\\juyil\\Dropbox\\Study\\GitHub\\Bayesian-gibbs-sampler\\R')
```

Setup
```{r}
itr_total = 12000
quantiles=c(0.1,0.5,0.9)
dist_eps_list=c("stdN","heteroN","student")

simulation1 = data.frame("Distribution_Eps"=character(0), "Method"=character(0),
                         "p"=numeric(), 
                         "beta1_MCSE"=numeric(), "beta1_IF"=numeric(), 
                         "beta2_MCSE"=numeric(), "beta2_IF"=numeric(), 
                         "beta3_MCSE"=numeric(), "beta3_IF"=numeric(), stringsAsFactors=F)

```

Append data
```{r}
for (p in quantiles){
    for (dist_eps in dist_eps_list){
        load(paste0("Gibbs with Scale\\","GWS_",p,"_",dist_eps,"_betap.RData"))
        beta_p = list()
        for (i in 1:3){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[2001:itr_total]
          plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "GWS", as.numeric(p), 
                    as.numeric(mcse(beta_p[[1]])$se), as.numeric(length(beta_p[[1]])/effectiveSize(beta_p[[1]])), 
                    as.numeric(mcse(beta_p[[2]])$se), as.numeric(length(beta_p[[2]])/effectiveSize(beta_p[[2]])), 
                    as.numeric(mcse(beta_p[[3]])$se), as.numeric(length(beta_p[[3]])/effectiveSize(beta_p[[3]])))
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################   
        load(paste0("Gibbs without Scale\\","GWOS_",p,"_",dist_eps,"_betap.RData"))
        beta_p = list()
        for (i in 1:3){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[2001:itr_total]
          plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "GWOS", as.numeric(p), 
                    as.numeric(mcse(beta_p[[1]])$se), as.numeric(length(beta_p[[1]])/effectiveSize(beta_p[[1]])), 
                    as.numeric(mcse(beta_p[[2]])$se), as.numeric(length(beta_p[[2]])/effectiveSize(beta_p[[2]])), 
                    as.numeric(mcse(beta_p[[3]])$se), as.numeric(length(beta_p[[3]])/effectiveSize(beta_p[[3]])))
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################
        load(paste0("Double Exponential Prior\\","DEP_",p,"_",dist_eps,"_betap.RData"))
        beta_p = list()
        for (i in 1:3){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[2001:itr_total]
          plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = c(dist_eps, "DEP", p,
                    mcse(beta_p[[1]])$se, length(beta_p[[1]])/effectiveSize(beta_p[[1]]),
                    mcse(beta_p[[2]])$se, length(beta_p[[2]])/effectiveSize(beta_p[[2]]),
                    mcse(beta_p[[3]])$se, length(beta_p[[3]])/effectiveSize(beta_p[[3]]))
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################
        load(paste0("Tobit with Scale\\","TWS_",p,"_",dist_eps,"_betap.RData"))
        beta_p = list()
        for (i in 1:3){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[2001:itr_total]
          plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "TWS", as.numeric(p), 
                    as.numeric(mcse(beta_p[[1]])$se), as.numeric(length(beta_p[[1]])/effectiveSize(beta_p[[1]])), 
                    as.numeric(mcse(beta_p[[2]])$se), as.numeric(length(beta_p[[2]])/effectiveSize(beta_p[[2]])), 
                    as.numeric(mcse(beta_p[[3]])$se), as.numeric(length(beta_p[[3]])/effectiveSize(beta_p[[3]])))
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################
        load(paste0("Tobit without Scale\\","TWOS_",p,"_",dist_eps,"_betap.RData"))
        beta_p = list()
        for (i in 1:3){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[2001:itr_total]
          plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "TWOS", as.numeric(p), 
                    as.numeric(mcse(beta_p[[1]])$se), as.numeric(length(beta_p[[1]])/effectiveSize(beta_p[[1]])), 
                    as.numeric(mcse(beta_p[[2]])$se), as.numeric(length(beta_p[[2]])/effectiveSize(beta_p[[2]])), 
                    as.numeric(mcse(beta_p[[3]])$se), as.numeric(length(beta_p[[3]])/effectiveSize(beta_p[[3]])))
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################
        
    }
}



```

Clean
```{r}
ord = c("stdN","heteroN","student")
simulation1$Distribution_Eps = factor(simulation1$Distribution_Eps,levels=ord)
simulation1 = simulation1[order(simulation1$Distribution_Eps),]
is.num <- sapply(simulation1, is.numeric)
simulation1[is.num] <- lapply(simulation1[is.num], round, 4)
simulation1

```






## Time comparison
Setup
```{r}
itr_total = 12000
quantiles=c(0.1,0.5,0.9)
dist_eps_list=c("stdN","heteroN","student")

simulation1 = data.frame("Distribution_Eps"=character(0), "Method"=character(0),
                         "p"=numeric(), t=numeric(), stringsAsFactors=F)

```


```{r}
for (p in quantiles){
    for (dist_eps in dist_eps_list){
        load(paste0("Gibbs with Scale\\","GWS_",p,"_",dist_eps,"_t.RData"))
        beta_p = list()
        for (i in 1:3){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[2001:itr_total]
          # plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "GWS", as.numeric(p), t)
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################   
        load(paste0("Gibbs without Scale\\","GWOS_",p,"_",dist_eps,"_t.RData"))
        beta_p = list()
        for (i in 1:3){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[2001:itr_total]
          # plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "GWOS", as.numeric(p), t)
        simulation1[nrow(simulation1)+1,] = new_obs
    
################################################################
        load(paste0("Tobit with Scale\\","TWS_",p,"_",dist_eps,"_t.RData"))
        beta_p = list()
        for (i in 1:3){
          beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[2001:itr_total]
          # plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        }
        new_obs = list(dist_eps, "TWS", as.numeric(p), t)
        simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################
        # load(paste0("Tobit without Scale\\","TWOS_",p,"_",dist_eps,"_t.RData"))
        # beta_p = list()
        # for (i in 1:3){
        #   beta_p[[i]]=unlist(lapply(beta_p_record, function(x){return(x[i,])}))[2001:itr_total]
        #   # plot(beta_p[[i]], type="l", main=paste("GWS_",p,"_",dist_eps,"_beta_",i), xlab="itr", ylab=paste("beta",i))
        # }
        # new_obs = list(dist_eps, "TWOS", as.numeric(p), t)
        # simulation1[nrow(simulation1)+1,] = new_obs
        
################################################################
        
    }
}
```

Clean
```{r}
ord = c("stdN","heteroN","student")
simulation1$Distribution_Eps = factor(simulation1$Distribution_Eps,levels=ord)
simulation1 = simulation1[order(simulation1$Distribution_Eps),]
is.num <- sapply(simulation1, is.numeric)
simulation1[is.num] <- lapply(simulation1[is.num], round, 4)
simulation1
```


